# ruff: noqa: E501
"""Layered COMSOL builders for topology-specific bearing models.

Every bearing family must register its own topology builder.  Contact, load,
mesh, solver, and result layers share small helpers, but cannot silently swap
one family's geometry for another.
"""

from __future__ import annotations

import math
from dataclasses import dataclass
from typing import Protocol

from comsol_agent.simulation.bearing_domain import (
    BearingModelInput,
    TaperedRollerParameters,
)


class UnsupportedBearingTopologyError(NotImplementedError):
    """Raised instead of substituting an unrelated bearing topology."""


@dataclass(frozen=True)
class TopologyManifest:
    family: str
    topology_builder: str
    ring_features: tuple[str, ...]
    rolling_element_features: tuple[str, ...]
    contact_pairs: tuple[str, ...]
    load_features: tuple[str, ...]
    support_features: tuple[str, ...]
    mesh_features: tuple[str, ...]
    result_features: tuple[str, ...]


@dataclass(frozen=True)
class ComsolBuildProduct:
    family: str
    model_name: str
    sections: dict[str, str]
    code: str
    manifest: TopologyManifest


class BearingTopologyBuilder(Protocol):
    family: str

    def build_topology(self, request: BearingModelInput) -> str: ...

    def build_contact(self, request: BearingModelInput) -> str: ...

    def build_loads_and_boundaries(self, request: BearingModelInput) -> str: ...

    def build_mesh(self, request: BearingModelInput) -> str: ...

    def build_solver(self, request: BearingModelInput) -> str: ...

    def build_results(self, request: BearingModelInput) -> str: ...

    def manifest(self, request: BearingModelInput) -> TopologyManifest: ...


class TaperedRollerComsolBuilder:
    """Full 3D cone/cup topology; never reuses cylindrical or ball geometry."""

    family = "tapered_roller"

    def build(self, request: BearingModelInput, *, model_name: str) -> ComsolBuildProduct:
        self._check_request(request)
        sections = {
            "parameters": self._build_parameters(request),
            "topology": self.build_topology(request),
            "contact": self.build_contact(request),
            "loads_boundaries": self.build_loads_and_boundaries(request),
            "mesh": self.build_mesh(request),
            "solver": self.build_solver(request),
            "results": self.build_results(request),
        }
        code = "\n".join(
            [
                "# Generated by TaperedRollerComsolBuilder from a validated BearingModelInput.",
                *sections.values(),
            ]
        )
        return ComsolBuildProduct(
            family=self.family,
            model_name=model_name,
            sections=sections,
            code=code,
            manifest=self.manifest(request),
        )

    def _check_request(self, request: BearingModelInput) -> None:
        if request.family != self.family or not isinstance(
            request.family_parameters, TaperedRollerParameters
        ):
            raise UnsupportedBearingTopologyError(
                "TaperedRollerComsolBuilder only accepts typed tapered_roller input."
            )

    def _build_parameters(self, request: BearingModelInput) -> str:
        common = request.common
        tapered = request.family_parameters
        assert isinstance(tapered, TaperedRollerParameters)
        values = {
            "inner_diameter": common.inner_diameter.comsol(),
            "outer_diameter": common.outer_diameter.comsol(),
            "bearing_width": common.bearing_width.comsol(),
            "pitch_diameter": common.pitch_diameter.comsol(),
            "roller_count": str(common.rolling_element_count),
            "roller_large_diameter": tapered.roller_large_diameter.comsol(),
            "roller_small_diameter": tapered.roller_small_diameter.comsol(),
            "roller_length": tapered.roller_length.comsol(),
            "roller_cone_angle": tapered.roller_cone_angle.comsol(),
            "inner_raceway_angle": tapered.inner_raceway_angle.comsol(),
            "outer_raceway_angle": tapered.outer_raceway_angle.comsol(),
            "contact_angle": tapered.contact_angle.comsol(),
            "flange_height": tapered.flange_height.comsol(),
            "flange_thickness": tapered.flange_thickness.comsol(),
            "initial_interference": tapered.initial_interference.comsol(),
            "axial_clearance": common.axial_clearance.comsol(),
            "friction_coefficient": common.friction_coefficient.comsol(),
            "mesh_bulk_size": common.mesh_bulk_size.comsol(),
            "mesh_contact_size": common.mesh_contact_size.comsol(),
            "radial_load_x": request.load.radial_x.comsol(),
            "radial_load_y": request.load.radial_y.comsol(),
            "axial_load": request.load.axial.comsol(),
            "moment_x": request.load.moment_x.comsol(),
            "moment_y": request.load.moment_y.comsol(),
            "load_steps": str(common.load_steps),
            "solver_relative_tolerance": f"{common.solver_relative_tolerance:.12g}",
            "E_steel": common.material.youngs_modulus.comsol(),
            "nu_steel": common.material.poisson_ratio.comsol(),
            "rho_steel": common.material.density.comsol(),
            "inner_stability_k": "1e5[N/m^3]",
            "roller_stability_k": "1e6[N/m^3]",
        }
        lines = [f"model.param().set({name!r}, {value!r});" for name, value in values.items()]
        lines.extend(
            [
                "model.param().set('pitch_radius', 'pitch_diameter/2');",
                "model.param().set('inner_bore_load_area', 'pi*inner_diameter*bearing_width');",
                "model.param().set('inner_race_mid_radius', 'pitch_radius-roller_length*sin(contact_angle)/2-roller_large_diameter*cos(contact_angle)/2+tan(inner_raceway_angle)*(roller_length*cos(contact_angle)/2-roller_large_diameter*sin(contact_angle)/2)+initial_interference');",
                "model.param().set('outer_race_mid_radius', 'pitch_radius-roller_length*sin(contact_angle)/2+roller_large_diameter*cos(contact_angle)/2+tan(outer_raceway_angle)*(roller_length*cos(contact_angle)/2+roller_large_diameter*sin(contact_angle)/2)-initial_interference');",
                "model.param().set('inner_race_r1', 'inner_race_mid_radius-tan(inner_raceway_angle)*bearing_width/2');",
                "model.param().set('inner_race_r2', 'inner_race_mid_radius+tan(inner_raceway_angle)*bearing_width/2');",
                "model.param().set('outer_race_r1', 'outer_race_mid_radius-tan(outer_raceway_angle)*bearing_width/2');",
                "model.param().set('outer_race_r2', 'outer_race_mid_radius+tan(outer_raceway_angle)*bearing_width/2');",
                "model.param().set('flange_contact_z', '-roller_length*cos(contact_angle)/2-tan(contact_angle)*(inner_race_r1+flange_height-(pitch_radius-roller_length*sin(contact_angle)/2))');",
                "model.param().set('load_scale', '1');",
            ]
        )
        return "\n".join(lines)

    def build_topology(self, request: BearingModelInput) -> str:
        common = request.common
        count = common.rolling_element_count
        tapered = request.family_parameters
        assert isinstance(tapered, TaperedRollerParameters)
        contact_angle = tapered.contact_angle.value_si
        pitch_radius_mm = common.pitch_diameter.in_unit("mm") / 2
        roller_length_mm = tapered.roller_length.in_unit("mm")
        lines = [
            "model.component().create('comp1', True);",
            "model.component('comp1').geom().create('geom1', 3);",
            "model.component('comp1').geom('geom1').lengthUnit('mm');",
            "geom = model.component('comp1').geom('geom1');",
            "geom.create('inner_race_cone', 'Cone');",
            "geom.feature('inner_race_cone').set('specifytop', 'radius');",
            "geom.feature('inner_race_cone').set('r', 'inner_race_r1');",
            "geom.feature('inner_race_cone').set('rtop', 'inner_race_r2');",
            "geom.feature('inner_race_cone').set('h', 'bearing_width');",
            "geom.feature('inner_race_cone').set('pos', ['0', '0', '-bearing_width/2']);",
            "geom.create('inner_bore', 'Cylinder');",
            "geom.feature('inner_bore').set('r', 'inner_diameter/2');",
            "geom.feature('inner_bore').set('h', 'bearing_width+2[mm]');",
            "geom.feature('inner_bore').set('pos', ['0', '0', '-bearing_width/2-1[mm]']);",
            "geom.create('inner_ring', 'Difference');",
            "geom.feature('inner_ring').selection('input').set(['inner_race_cone']);",
            "geom.feature('inner_ring').selection('input2').set(['inner_bore']);",
            "geom.feature('inner_ring').set('selresult', 'on');",
            "geom.feature('inner_ring').set('selresultshow', 'all');",
            "geom.create('outer_envelope', 'Cylinder');",
            "geom.feature('outer_envelope').set('r', 'outer_diameter/2');",
            "geom.feature('outer_envelope').set('h', 'bearing_width');",
            "geom.feature('outer_envelope').set('pos', ['0', '0', '-bearing_width/2']);",
            "geom.create('outer_race_void', 'Cone');",
            "geom.feature('outer_race_void').set('specifytop', 'radius');",
            "geom.feature('outer_race_void').set('r', 'outer_race_r1');",
            "geom.feature('outer_race_void').set('rtop', 'outer_race_r2');",
            "geom.feature('outer_race_void').set('h', 'bearing_width+2[mm]');",
            "geom.feature('outer_race_void').set('pos', ['0', '0', '-bearing_width/2-1[mm]']);",
            "geom.create('outer_ring', 'Difference');",
            "geom.feature('outer_ring').selection('input').set(['outer_envelope']);",
            "geom.feature('outer_ring').selection('input2').set(['outer_race_void']);",
            "geom.feature('outer_ring').set('selresult', 'on');",
            "geom.feature('outer_ring').set('selresultshow', 'all');",
            # A tapered bearing rib must present an inclined face to the large
            # roller end. A flat cylinder face permits non-physical axial slide.
            "geom.create('inner_flange_blank', 'Cone');",
            "geom.feature('inner_flange_blank').set('specifytop', 'radius');",
            "geom.feature('inner_flange_blank').set('r', 'inner_race_r1+flange_height');",
            "geom.feature('inner_flange_blank').set('rtop', 'inner_race_r1');",
            "geom.feature('inner_flange_blank').set('h', 'flange_height*tan(contact_angle)');",
            "geom.feature('inner_flange_blank').set('pos', ['0', '0', 'flange_contact_z']);",
            "geom.create('inner_flange_bore', 'Cylinder');",
            "geom.feature('inner_flange_bore').set('r', 'inner_diameter/2');",
            "geom.feature('inner_flange_bore').set('h', 'flange_height*tan(contact_angle)+2[mm]');",
            "geom.feature('inner_flange_bore').set('pos', ['0', '0', 'flange_contact_z-1[mm]']);",
            "geom.create('inner_flange', 'Difference');",
            "geom.feature('inner_flange').selection('input').set(['inner_flange_blank']);",
            "geom.feature('inner_flange').selection('input2').set(['inner_flange_bore']);",
            "geom.feature('inner_flange').set('selresult', 'on');",
            "geom.feature('inner_flange').set('selresultshow', 'all');",
            "geom.create('inner_ring_complete', 'Union');",
            "geom.feature('inner_ring_complete').selection('input').set(['inner_ring', 'inner_flange']);",
            "geom.feature('inner_ring_complete').set('selresult', 'on');",
            "geom.feature('inner_ring_complete').set('selresultshow', 'all');",
        ]
        rolling_elements: list[str] = []
        final_roller_objects: dict[int, str] = {}
        for index in range(1, count + 1):
            theta = 2 * math.pi * (index - 1) / count
            axis = (
                math.sin(contact_angle) * math.cos(theta),
                math.sin(contact_angle) * math.sin(theta),
                math.cos(contact_angle),
            )
            center = (
                pitch_radius_mm * math.cos(theta),
                pitch_radius_mm * math.sin(theta),
                0.0,
            )
            base = tuple(center[i] - axis[i] * roller_length_mm / 2 for i in range(3))
            tag = f"tapered_roller_{index}"
            rolling_elements.append(tag)
            lines.extend(
                [
                    f"geom.create('{tag}', 'Cone');",
                    f"geom.feature('{tag}').set('specifytop', 'radius');",
                    f"geom.feature('{tag}').set('r', 'roller_large_diameter/2');",
                    f"geom.feature('{tag}').set('rtop', 'roller_small_diameter/2');",
                    f"geom.feature('{tag}').set('h', 'roller_length');",
                    f"geom.feature('{tag}').set('axis', {_vec(axis)});",
                    f"geom.feature('{tag}').set('pos', {_vec_mm(base)});",
                    f"geom.feature('{tag}').set('selresult', 'on');",
                    f"geom.feature('{tag}').set('selresultshow', 'all');",
                ]
            )
        mean_radius_mm = (
            tapered.roller_large_diameter.in_unit("mm")
            + tapered.roller_small_diameter.in_unit("mm")
        ) / 4
        current_ring_objects = {
            "inner": "inner_ring_complete",
            "outer": "outer_ring",
        }
        partition_indices: tuple[int, ...] = ()
        for index in partition_indices:
            theta = 2 * math.pi * (index - 1) / count
            for side, direction in (("inner", -1), ("outer", 1)):
                contact_radius = pitch_radius_mm + direction * mean_radius_mm * math.cos(
                    contact_angle
                )
                center = (
                    contact_radius * math.cos(theta),
                    contact_radius * math.sin(theta),
                    0.0,
                )
                tool = f"partition_tool_{side}_{index}"
                partition = f"partition_{side}_{index}"
                lines.extend(
                    [
                        f"geom.create('{tool}', 'Block');",
                        f"geom.feature('{tool}').set('base', 'center');",
                        f"geom.feature('{tool}').set('size', ['4[mm]', '3[mm]', 'bearing_width+2[mm]']);",
                        f"geom.feature('{tool}').set('pos', {_vec_mm(center)});",
                        f"geom.feature('{tool}').set('rot', '{math.degrees(theta):.12g}[deg]');",
                        f"geom.create('{partition}', 'Partition');",
                        f"geom.feature('{partition}').selection('input').set(['{current_ring_objects[side]}']);",
                        f"geom.feature('{partition}').selection('tool').set(['{tool}']);",
                        f"geom.feature('{partition}').set('keepinput', 'off');",
                        f"geom.feature('{partition}').set('keeptool', 'off');",
                        f"geom.feature('{partition}').set('selresult', 'on');",
                        f"geom.feature('{partition}').set('selresultshow', 'all');",
                    ]
                )
                current_ring_objects[side] = partition
        for index in partition_indices:
            theta = 2 * math.pi * (index - 1) / count
            current_roller_object = f"tapered_roller_{index}"
            for side, direction in (("inner", -1), ("outer", 1)):
                contact_radius = pitch_radius_mm + direction * mean_radius_mm * math.cos(
                    contact_angle
                )
                center = (
                    contact_radius * math.cos(theta),
                    contact_radius * math.sin(theta),
                    -direction * mean_radius_mm * math.sin(contact_angle),
                )
                tool = f"partition_tool_roller_{index}_{side}"
                partition = f"partition_roller_{index}_{side}"
                lines.extend(
                    [
                        f"geom.create('{tool}', 'Block');",
                        f"geom.feature('{tool}').set('base', 'center');",
                        f"geom.feature('{tool}').set('size', ['4[mm]', '3[mm]', 'bearing_width+4[mm]']);",
                        f"geom.feature('{tool}').set('pos', {_vec_mm(center)});",
                        f"geom.feature('{tool}').set('rot', '{math.degrees(theta):.12g}[deg]');",
                        f"geom.create('{partition}', 'Partition');",
                        f"geom.feature('{partition}').selection('input').set(['{current_roller_object}']);",
                        f"geom.feature('{partition}').selection('tool').set(['{tool}']);",
                        f"geom.feature('{partition}').set('keepinput', 'off');",
                        f"geom.feature('{partition}').set('keeptool', 'off');",
                        f"geom.feature('{partition}').set('selresult', 'on');",
                        f"geom.feature('{partition}').set('selresultshow', 'all');",
                    ]
                )
                current_roller_object = partition
            final_roller_objects[index] = current_roller_object
        for side in (("inner", "outer") if partition_indices else ()):
            union = f"partitioned_{side}_ring"
            lines.extend(
                [
                    f"geom.create('{union}', 'Union');",
                    f"geom.feature('{union}').selection('input').set(['{current_ring_objects[side]}']);",
                    f"geom.feature('{union}').set('intbnd', 'on');",
                    f"geom.feature('{union}').set('selresult', 'on');",
                    f"geom.feature('{union}').set('selresultshow', 'all');",
                ]
            )
        for index in partition_indices:
            union = f"partitioned_roller_{index}"
            lines.extend(
                [
                    f"geom.create('{union}', 'Union');",
                    f"geom.feature('{union}').selection('input').set(['{final_roller_objects[index]}']);",
                    f"geom.feature('{union}').set('intbnd', 'on');",
                    f"geom.feature('{union}').set('selresult', 'on');",
                    f"geom.feature('{union}').set('selresultshow', 'all');",
                ]
            )
        lines.extend(
            [
                "geom.feature('fin').set('action', 'assembly');",
                "geom.feature('fin').set('createpairs', 'off');",
                "geom.run();",
                f"output.write('TOPOLOGY|family=tapered_roller|rollers={count}|features=inner_ring,outer_ring,inner_flange,{','.join(rolling_elements)}\\n');",
            ]
        )
        return "\n".join(lines)

    def build_contact(self, request: BearingModelInput) -> str:
        count = request.common.rolling_element_count
        pitch_radius = request.common.pitch_diameter.in_unit("mm") / 2
        tapered = request.family_parameters
        assert isinstance(tapered, TaperedRollerParameters)
        mean_radius = (
            tapered.roller_large_diameter.in_unit("mm")
            + tapered.roller_small_diameter.in_unit("mm")
        ) / 4
        contact_angle = tapered.contact_angle.value_si
        lines = [
            "comp = model.component('comp1');",
            "comp.physics().create('solid', 'SolidMechanics', 'geom1');",
            "solid = comp.physics('solid');",
        ]
        roller_selections: dict[str, list[str]] = {"inner": [], "outer": []}
        raceway_selections: dict[str, list[str]] = {"inner": [], "outer": []}
        for index in range(1, count + 1):
            theta = 2 * math.pi * (index - 1) / count
            radial = (math.cos(theta), math.sin(theta))
            for side, direction, ring_object in (
                ("inner", -1, "geom1_inner_ring_complete_bnd"),
                ("outer", 1, "geom1_outer_ring_bnd"),
            ):
                contact_radius = pitch_radius + direction * mean_radius * math.cos(
                    contact_angle
                )
                center = (
                    contact_radius * radial[0],
                    contact_radius * radial[1],
                    -direction * mean_radius * math.sin(contact_angle),
                )
                ball = f"ball_roller_{index}_{side}_contact"
                roller_selection = f"sel_roller_{index}_{side}_contact"
                ring_selection = f"sel_{side}_raceway_{index}_contact"
                roller_selections[side].append(roller_selection)
                raceway_selections[side].append(ring_selection)
                lines.extend(
                    [
                        f"comp.selection().create('{ball}', 'Ball');",
                        f"comp.selection('{ball}').set('entitydim', '2');",
                        f"comp.selection('{ball}').set('posx', '{center[0]:.12g}[mm]');",
                        f"comp.selection('{ball}').set('posy', '{center[1]:.12g}[mm]');",
                        f"comp.selection('{ball}').set('posz', '{center[2]:.12g}[mm]');",
                        f"comp.selection('{ball}').set('r', '1[mm]');",
                        f"comp.selection('{ball}').set('condition', 'intersects');",
                        f"comp.selection().create('{roller_selection}', 'Intersection');",
                        f"comp.selection('{roller_selection}').set('entitydim', '2');",
                        f"comp.selection('{roller_selection}').set('input', ['{ball}', 'geom1_tapered_roller_{index}_bnd']);",
                        f"comp.selection().create('{ring_selection}', 'Intersection');",
                        f"comp.selection('{ring_selection}').set('entitydim', '2');",
                        f"comp.selection('{ring_selection}').set('input', ['{ball}', '{ring_object}']);",
                        f"output.write('CONTACT_SELECTION|interface=roller_{index}_{side}|source=' + str(len(list(comp.selection('{roller_selection}').entities()))) + '|destination=' + str(len(list(comp.selection('{ring_selection}').entities()))) + '\\n');",
                        f"comp.pair().create('cp_roller_{index}_{side}', 'Contact');",
                        f"comp.pair('cp_roller_{index}_{side}').manualSelection(True);",
                        f"comp.pair('cp_roller_{index}_{side}').source().named('{roller_selection}');",
                        f"comp.pair('cp_roller_{index}_{side}').destination().named('{ring_selection}');",
                        f"solid.create('contact_roller_{index}_{side}', 'Contact', 2);",
                        f"solid.feature('contact_roller_{index}_{side}').set('pairs', ['cp_roller_{index}_{side}']);",
                        f"solid.feature('contact_roller_{index}_{side}').set('pfm', 'penalty');",
                        f"solid.feature('contact_roller_{index}_{side}').set('penaltyCtrl', 'userDefined');",
                        f"solid.feature('contact_roller_{index}_{side}').set('pn_penalty', 'E_steel/mesh_contact_size');",
                        f"solid.feature('contact_roller_{index}_{side}').set('zeroInitGap', '1');",
                        f"solid.feature('contact_roller_{index}_{side}').set('ContactTolType', 'Manual');",
                        f"solid.feature('contact_roller_{index}_{side}').set('tolcontact', 'mesh_contact_size');",
                        f"solid.feature('contact_roller_{index}_{side}').set('useRelaxation', 'Always');",
                        f"solid.feature('contact_roller_{index}_{side}').set('irlx', '0.05');",
                        *(
                            [
                                f"solid.feature('contact_roller_{index}_{side}').create('friction_{index}_{side}', 'Friction');",
                                f"solid.feature('contact_roller_{index}_{side}').feature('friction_{index}_{side}').set('FrictionModel', 'StaticFriction');",
                                f"solid.feature('contact_roller_{index}_{side}').feature('friction_{index}_{side}').set('mustat', 'friction_coefficient');",
                            ]
                            if request.common.friction_coefficient.value_si > 0
                            else []
                        ),
                    ]
                )
            flange_ball = f"ball_roller_{index}_flange_contact"
            roller_flange_selection = f"sel_roller_{index}_flange_contact"
            flange_selection = f"sel_flange_{index}_contact"
            roller_flange_candidates = f"candidates_roller_{index}_flange_contact"
            flange_candidates = f"candidates_flange_{index}_contact"
            large_end_area_mm2 = math.pi * (
                tapered.roller_large_diameter.in_unit("mm") / 2
            ) ** 2
            lines.extend(
                [
                    f"comp.selection().create('{flange_ball}', 'Ball');",
                    f"comp.selection('{flange_ball}').set('entitydim', '2');",
                    f"comp.selection('{flange_ball}').set('posx', '{math.cos(theta):.12g}*(inner_race_r1+flange_height)');",
                    f"comp.selection('{flange_ball}').set('posy', '{math.sin(theta):.12g}*(inner_race_r1+flange_height)');",
                    f"comp.selection('{flange_ball}').set('posz', 'flange_contact_z');",
                    f"comp.selection('{flange_ball}').set('r', '1[mm]');",
                    f"comp.selection('{flange_ball}').set('condition', 'intersects');",
                    f"comp.selection().create('{roller_flange_candidates}', 'Intersection');",
                    f"comp.selection('{roller_flange_candidates}').set('entitydim', '2');",
                    f"comp.selection('{roller_flange_candidates}').set('input', ['{flange_ball}', 'geom1_tapered_roller_{index}_bnd']);",
                    f"comp.selection().create('{flange_candidates}', 'Intersection');",
                    f"comp.selection('{flange_candidates}').set('entitydim', '2');",
                    f"comp.selection('{flange_candidates}').set('input', ['{flange_ball}', 'geom1_inner_flange_bnd']);",
                    "flange_measure = comp.geom('geom1').measureFinal();",
                    f"roller_candidate_entities = list(comp.selection('{roller_flange_candidates}').entities());",
                    "roller_end_entity = None",
                    "roller_end_area_error = float('inf')",
                    "for candidate_entity in roller_candidate_entities:",
                    "    flange_measure.selection().geom(2)",
                    "    flange_measure.selection().set([int(candidate_entity)])",
                    f"    area_error = abs(float(flange_measure.getArea()) - {large_end_area_mm2:.12g})",
                    "    if area_error < roller_end_area_error:",
                    "        roller_end_area_error = area_error",
                    "        roller_end_entity = int(candidate_entity)",
                    f"comp.selection().create('{roller_flange_selection}', 'Explicit');",
                    f"comp.selection('{roller_flange_selection}').geom('geom1', 2);",
                    f"comp.selection('{roller_flange_selection}').set([roller_end_entity] if roller_end_entity is not None else []);",
                    f"flange_candidate_entities = list(comp.selection('{flange_candidates}').entities());",
                    "flange_face_entities = []",
                    "for candidate_entity in flange_candidate_entities:",
                    "    flange_measure.selection().geom(2)",
                    "    flange_measure.selection().set([int(candidate_entity)])",
                    "    candidate_bbox = list(flange_measure.getBoundingBox())",
                    "    if abs(float(candidate_bbox[5]) - float(candidate_bbox[4])) > 1e-8:",
                    "        flange_face_entities.append(int(candidate_entity))",
                    f"comp.selection().create('{flange_selection}', 'Explicit');",
                    f"comp.selection('{flange_selection}').geom('geom1', 2);",
                    f"comp.selection('{flange_selection}').set(flange_face_entities);",
                    f"output.write('CONTACT_SELECTION|interface=roller_{index}_flange|source=' + str(len(list(comp.selection('{roller_flange_selection}').entities()))) + '|destination=' + str(len(list(comp.selection('{flange_selection}').entities()))) + '\\n');",
                    f"comp.pair().create('cp_roller_{index}_flange', 'Contact');",
                    f"comp.pair('cp_roller_{index}_flange').manualSelection(True);",
                    f"comp.pair('cp_roller_{index}_flange').source().named('{roller_flange_selection}');",
                    f"comp.pair('cp_roller_{index}_flange').destination().named('{flange_selection}');",
                    f"solid.create('contact_roller_{index}_flange', 'Contact', 2);",
                    f"solid.feature('contact_roller_{index}_flange').set('pairs', ['cp_roller_{index}_flange']);",
                    f"solid.feature('contact_roller_{index}_flange').set('pfm', 'penalty');",
                    f"solid.feature('contact_roller_{index}_flange').set('penaltyCtrl', 'userDefined');",
                    f"solid.feature('contact_roller_{index}_flange').set('pn_penalty', 'E_steel/mesh_contact_size');",
                    f"solid.feature('contact_roller_{index}_flange').set('zeroInitGap', '0');",
                    f"solid.feature('contact_roller_{index}_flange').set('ContactTolType', 'Manual');",
                    f"solid.feature('contact_roller_{index}_flange').set('tolcontact', 'mesh_contact_size');",
                    f"solid.feature('contact_roller_{index}_flange').set('useRelaxation', 'Always');",
                    f"solid.feature('contact_roller_{index}_flange').set('irlx', '0.05');",
                ]
            )
        for side in ("inner", "outer"):
            sources = ", ".join(repr(tag) for tag in roller_selections[side])
            destinations = ", ".join(repr(tag) for tag in raceway_selections[side])
            lines.extend(
                [
                    f"comp.selection().create('sel_all_roller_{side}_contacts', 'Union');",
                    f"comp.selection('sel_all_roller_{side}_contacts').set('entitydim', '2');",
                    f"comp.selection('sel_all_roller_{side}_contacts').set('input', [{sources}]);",
                    f"comp.selection().create('sel_all_{side}_raceway_contacts', 'Union');",
                    f"comp.selection('sel_all_{side}_raceway_contacts').set('entitydim', '2');",
                    f"comp.selection('sel_all_{side}_raceway_contacts').set('input', [{destinations}]);",
                ]
            )
        lines.append(
            f"output.write('CONTACT|policy={'static_coulomb' if request.common.friction_coefficient.value_si > 0 else 'frictionless'}|coefficient=friction_coefficient|pairs={3 * count}|status=created\\n');"
        )
        return "\n".join(lines)

    def build_loads_and_boundaries(self, request: BearingModelInput) -> str:
        lines = [
                "solid = model.component('comp1').physics('solid');",
                "comp = model.component('comp1');",
                "model.component('comp1').material().create('mat_steel', 'Common');",
                "mat = model.component('comp1').material('mat_steel');",
                "mat.propertyGroup('def').set('youngsmodulus', 'E_steel');",
                "mat.propertyGroup('def').set('poissonsratio', 'nu_steel');",
                "mat.propertyGroup('def').set('density', 'rho_steel');",
                "solid.create('fix_outer', 'Fixed', 2);",
                "solid.feature('fix_outer').selection().named('geom1_outer_ring_bnd');",
                "for bore_point, bore_xy in {'px': ('inner_diameter/2', '0'), 'nx': ('-inner_diameter/2', '0'), 'py': ('0', 'inner_diameter/2'), 'ny': ('0', '-inner_diameter/2')}.items():",
                "    comp.selection().create('ball_inner_bore_' + bore_point, 'Ball')",
                "    comp.selection('ball_inner_bore_' + bore_point).set('entitydim', '2')",
                "    comp.selection('ball_inner_bore_' + bore_point).set('posx', bore_xy[0])",
                "    comp.selection('ball_inner_bore_' + bore_point).set('posy', bore_xy[1])",
                "    comp.selection('ball_inner_bore_' + bore_point).set('posz', '0')",
                "    comp.selection('ball_inner_bore_' + bore_point).set('r', '1[mm]')",
                "    comp.selection('ball_inner_bore_' + bore_point).set('condition', 'intersects')",
                "comp.selection().create('sel_inner_bore_points', 'Union');",
                "comp.selection('sel_inner_bore_points').set('entitydim', '2');",
                "comp.selection('sel_inner_bore_points').set('input', ['ball_inner_bore_px', 'ball_inner_bore_nx', 'ball_inner_bore_py', 'ball_inner_bore_ny']);",
                "comp.selection().create('sel_inner_bore_load', 'Intersection');",
                "comp.selection('sel_inner_bore_load').set('entitydim', '2');",
                "comp.selection('sel_inner_bore_load').set('input', ['sel_inner_bore_points', 'geom1_inner_ring_complete_bnd']);",
                "output.write('LOAD_SELECTION|inner_bore_boundaries=' + str(len(list(comp.selection('sel_inner_bore_load').entities()))) + '\\n');",
                "comp.cpl().create('intop_inner_bore_load', 'Integration');",
                "comp.cpl('intop_inner_bore_load').selection().named('sel_inner_bore_load');",
                "solid.create('load_inner', 'BoundaryLoad', 2);",
                "solid.feature('load_inner').selection().named('sel_inner_bore_load');",
                "solid.feature('load_inner').set('FperArea', ['load_scale*radial_load_x/intop_inner_bore_load(1)', 'load_scale*radial_load_y/intop_inner_bore_load(1)', 'load_scale*axial_load/intop_inner_bore_load(1)']);",
            ]
        has_axial_location = abs(request.load.axial.value_si) <= 1e-12
        if has_axial_location:
            lines.extend(
                [
                    "solid.create('axial_locate_inner', 'Displacement2', 2);",
                    "solid.feature('axial_locate_inner').selection().named('geom1_inner_ring_complete_bnd');",
                    "solid.feature('axial_locate_inner').set('Direction', ['0', '0', '1']);",
                    "solid.feature('axial_locate_inner').set('U0', ['0', '0', '0']);",
                ]
            )
        lines.extend(
            [
                "solid.create('inner_stability', 'SpringFoundation2', 2);",
                "solid.feature('inner_stability').selection().named('geom1_inner_ring_complete_bnd');",
                "solid.feature('inner_stability').set('SpringType', 'kPerArea');",
                "solid.feature('inner_stability').set('kPerArea', ['inner_stability_k', 'inner_stability_k', 'inner_stability_k']);",
                "comp.selection().create('sel_all_roller_boundaries', 'Union');",
                "comp.selection('sel_all_roller_boundaries').set('entitydim', '2');",
                "comp.selection('sel_all_roller_boundaries').set('input', ["
                + ", ".join(
                    repr(f"geom1_tapered_roller_{index}_bnd")
                    for index in range(1, request.common.rolling_element_count + 1)
                )
                + "]);",
                "solid.create('roller_stability', 'SpringFoundation2', 2);",
                "solid.feature('roller_stability').selection().named('sel_all_roller_boundaries');",
                "solid.feature('roller_stability').set('SpringType', 'kPerArea');",
                "solid.feature('roller_stability').set('kPerArea', ['roller_stability_k', 'roller_stability_k', 'roller_stability_k']);",
            ]
        )
        physical_support = (
            "outer_ring_fixed,inner_ring_axial_location"
            if has_axial_location
            else "outer_ring_fixed,physical_tapered_raceway_and_rib"
        )
        lines.append(
            f"output.write('BOUNDARY|support={physical_support}|load=inner_bore_FperArea|components=radial_x,radial_y,axial|stabilization=explicit_weak_foundations_with_postsolve_equilibrium_audit\\n');"
        )
        return "\n".join(lines)

    def build_mesh(self, request: BearingModelInput) -> str:
        return "\n".join(
            [
                "model.component('comp1').mesh().create('mesh1');",
                "mesh = model.component('comp1').mesh('mesh1');",
                "mesh.create('size_bulk', 'Size');",
                "mesh.feature('size_bulk').set('custom', 'on');",
                "mesh.feature('size_bulk').set('hmax', 'mesh_bulk_size');",
                "mesh.feature('size_bulk').set('hmin', 'mesh_contact_size/3');",
                "mesh.create('ftet1', 'FreeTet');",
                "mesh.run();",
            ]
        )

    def build_solver(self, request: BearingModelInput) -> str:
        return "\n".join(
            [
                "model.study().create('std1');",
                "model.study('std1').create('stat', 'Stationary');",
                "model.study('std1').feature('stat').set('useparam', 'on');",
                "model.study('std1').feature('stat').set('pname', ['load_scale']);",
                "model.study('std1').feature('stat').set('plistarr', ['1e-5 2e-5 5e-5 1e-4 2e-4 5e-4 0.001 0.002 0.005 0.01 0.02 0.05 0.1 0.2 0.5 1']);",
                "model.study('std1').createAutoSequences('sol');",
                "stationary_solver = model.sol('sol1').feature('s1');",
                "stationary_solver.set('stol', 'solver_relative_tolerance');",
                "stationary_solver.feature('se1').set('maxsegiter', '100');",
                "stationary_solver.feature('se1').set('segiter', '100');",
                "stationary_solver.feature('se1').set('ntolfact', '1');",
                "output.write('SOLVER_TREE|s1=' + str(list(model.sol('sol1').feature('s1').feature().tags())) + '\\n');",
                "for child_tag in list(model.sol('sol1').feature('s1').feature().tags()):",
                "    try:",
                "        child = model.sol('sol1').feature('s1').feature(str(child_tag))",
                "        output.write('SOLVER_CHILD|' + str(child_tag) + '=' + str(list(child.feature().tags())) + '\\n')",
                "    except Exception:",
                "        pass",
            ]
        )

    def build_results(self, request: BearingModelInput) -> str:
        return "\n".join(
            [
                "model.result().create('pg_stress3d', 'PlotGroup3D');",
                "model.result('pg_stress3d').create('surf_stress', 'Surface');",
                "model.result('pg_stress3d').feature('surf_stress').set('expr', 'solid.mises');",
                "model.result().numerical().create('max_von_mises', 'MaxVolume');",
                "model.result().numerical('max_von_mises').set('expr', ['solid.mises']);",
            ]
        )

    def manifest(self, request: BearingModelInput) -> TopologyManifest:
        count = request.common.rolling_element_count
        return TopologyManifest(
            family=self.family,
            topology_builder=self.__class__.__name__,
            ring_features=("inner_ring_complete", "outer_ring"),
            rolling_element_features=tuple(f"tapered_roller_{i}" for i in range(1, count + 1)),
            contact_pairs=tuple(
                f"cp_roller_{i}_{side}"
                for i in range(1, count + 1)
                for side in ("inner", "outer", "flange")
            ),
            load_features=("load_inner",),
            support_features=(
                "fix_outer",
                *(("axial_locate_inner",) if abs(request.load.axial.value_si) <= 1e-12 else ()),
                "inner_stability",
                "roller_stability",
            ),
            mesh_features=("size_bulk", "ftet1"),
            result_features=("pg_stress3d", "max_von_mises"),
        )


_BUILDERS: dict[str, BearingTopologyBuilder] = {
    "tapered_roller": TaperedRollerComsolBuilder(),
}


def get_bearing_builder(family: str) -> BearingTopologyBuilder:
    try:
        return _BUILDERS[family]
    except KeyError as exc:
        raise UnsupportedBearingTopologyError(
            f"No COMSOL topology builder is implemented for {family!r}; topology substitution is forbidden."
        ) from exc


def build_comsol_bearing(request: BearingModelInput, *, model_name: str) -> ComsolBuildProduct:
    builder = get_bearing_builder(request.family)
    build = getattr(builder, "build", None)
    if build is None:
        raise UnsupportedBearingTopologyError(
            f"Registered builder for {request.family!r} does not implement a full layered build."
        )
    return build(request, model_name=model_name)


def _vec(values: tuple[float, float, float]) -> str:
    return "[" + ", ".join(repr(f"{value:.12g}") for value in values) + "]"


def _vec_mm(values: tuple[float, float, float]) -> str:
    return "[" + ", ".join(repr(f"{value:.12g}[mm]") for value in values) + "]"
