"""Public V2 COMSOL runtime API."""

from .artifacts import ArtifactStore
from .backend import (
    BackendCapabilities,
    BackendWorker,
    FakeWorkerExecutor,
    InProcessWorkerExecutor,
    MphBackendAdapter,
)
from .contracts import (
    RUNTIME_SCHEMA_VERSION,
    CancelRunRequest,
    Checkpoint,
    CheckpointCreateRequest,
    CheckpointInspectRequest,
    CheckpointRestoreRequest,
    ErrorClass,
    EvaluateRequest,
    ExportRequest,
    FailureInspectRequest,
    ModelActionRequest,
    ModelCloseRequest,
    ModelCreateRequest,
    ModelLoadRequest,
    ModelSaveRequest,
    ParameterPatchRequest,
    RegisteredExecutionRequest,
    RuntimeArtifact,
    RuntimeFailure,
    RuntimeOperation,
    RuntimeProvenance,
    RuntimeResult,
    RuntimeRunRequest,
    RuntimeStage,
    SessionStatus,
    SessionStatusRequest,
    StageRecord,
    StageState,
)
from .errors import (
    CheckpointCompatibilityError,
    ComsolRuntimeError,
    PhysicalAuditError,
    ResourceLeaseError,
    classify_backend_error,
)
from .mcp import RuntimeMcpTool, build_mcp_tools
from .service import RUNTIME_VERSION, ComsolRuntime

__all__ = [
    "RUNTIME_SCHEMA_VERSION",
    "RUNTIME_VERSION",
    "ArtifactStore",
    "BackendCapabilities",
    "BackendWorker",
    "CancelRunRequest",
    "Checkpoint",
    "CheckpointCompatibilityError",
    "CheckpointCreateRequest",
    "CheckpointInspectRequest",
    "CheckpointRestoreRequest",
    "ComsolRuntime",
    "ComsolRuntimeError",
    "ErrorClass",
    "EvaluateRequest",
    "ExportRequest",
    "FailureInspectRequest",
    "FakeWorkerExecutor",
    "InProcessWorkerExecutor",
    "ModelActionRequest",
    "ModelCloseRequest",
    "ModelCreateRequest",
    "ModelLoadRequest",
    "ModelSaveRequest",
    "MphBackendAdapter",
    "ParameterPatchRequest",
    "PhysicalAuditError",
    "RegisteredExecutionRequest",
    "ResourceLeaseError",
    "RuntimeArtifact",
    "RuntimeFailure",
    "RuntimeMcpTool",
    "RuntimeOperation",
    "RuntimeProvenance",
    "RuntimeResult",
    "RuntimeRunRequest",
    "RuntimeStage",
    "SessionStatus",
    "SessionStatusRequest",
    "StageRecord",
    "StageState",
    "build_mcp_tools",
    "classify_backend_error",
]
