"""Public V2 dynamic extension API."""

from .errors import (
    DependentExtensionError,
    DuplicateExtensionError,
    ExtensionConflictError,
    ExtensionError,
    ExtensionInvocationError,
    ExtensionNotFoundError,
    ExtensionStateError,
    ExtensionValidationError,
    MissingDependencyError,
)
from .executor import RegistryToolExecutor
from .interfaces import (
    AuditorExtension,
    BuilderExtension,
    DeterministicPathExtension,
    Extension,
    FunctionExtension,
    HookExtension,
    McpServerExtension,
    McpToolExtension,
    MemoryAdapterExtension,
    RepairRuleExtension,
    RetrieverExtension,
    SkillExtension,
    ValidatorExtension,
)
from .loader import ExtensionLoader
from .models import (
    API_VERSION,
    CandidateState,
    CapabilityRequirement,
    CompatibilitySpec,
    ComsolPermission,
    ConflictReport,
    DependencySpec,
    ExtensionCandidate,
    ExtensionKind,
    ExtensionManifest,
    FilesystemPermission,
    HealthReport,
    HealthStatus,
    LifecycleEvent,
    LifecycleState,
    NetworkPermission,
    PermissionSet,
    Registration,
    ResolutionContext,
    ShellPermission,
    ValidationIssue,
    ValidationResult,
)
from .policy import CompatibilityPolicy, PermissionPolicy
from .registry import ExtensionRegistry, ExtensionSnapshot

__all__ = [
    "API_VERSION",
    "AuditorExtension",
    "BuilderExtension",
    "CapabilityRequirement",
    "CandidateState",
    "ComsolPermission",
    "CompatibilityPolicy",
    "CompatibilitySpec",
    "ConflictReport",
    "DependencySpec",
    "DependentExtensionError",
    "DeterministicPathExtension",
    "DuplicateExtensionError",
    "Extension",
    "ExtensionCandidate",
    "ExtensionConflictError",
    "ExtensionError",
    "ExtensionInvocationError",
    "ExtensionKind",
    "ExtensionLoader",
    "ExtensionManifest",
    "ExtensionNotFoundError",
    "ExtensionRegistry",
    "ExtensionSnapshot",
    "ExtensionStateError",
    "ExtensionValidationError",
    "FilesystemPermission",
    "FunctionExtension",
    "HealthReport",
    "HealthStatus",
    "HookExtension",
    "LifecycleEvent",
    "LifecycleState",
    "McpServerExtension",
    "McpToolExtension",
    "MemoryAdapterExtension",
    "MissingDependencyError",
    "NetworkPermission",
    "PermissionPolicy",
    "PermissionSet",
    "Registration",
    "RegistryToolExecutor",
    "RepairRuleExtension",
    "ResolutionContext",
    "RetrieverExtension",
    "ShellPermission",
    "SkillExtension",
    "ValidationIssue",
    "ValidationResult",
    "ValidatorExtension",
]
